baseURL = "https://shilohc.github.io/blog/"
languageCode = "en-us"
canonifyURLs = true
enableEmoji = true
googleAnalytics = ""
theme = "pristine"
summaryLength = 25
publishDir = "docs"
pygmentsCodeFences = true

[params]
  title = "emerg*nt misbeh@vior"
  google_fonts = [
    ["Fira Code", "400, 700"],
    ["Ovo", "400"]
  ]
  heading_font = "Fira Code"
  body_font = "Open Sans"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "algol_nu"
    tabWidth = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "All Posts"
  url = "/all/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "Blogroll"
  url = "/blogroll/"
  weight = 4

[[params.social]]
  title = "Email"
  url = "mailto:shilohc@mit.edu"
[[params.social]]
  title = "Github"
  url = "https://github.com/shilohc"
